#!/bin/sh

set -x
set -e

if [[ ! -z "${JIANMU_WORKSPACE}" ]]; then
    cd ${JIANMU_WORKSPACE}
fi

if [[ ! -z "${JIANMU_MIRROR_REGISTRY_URL}" ]]; then
    npm config set registry "${JIANMU_MIRROR_REGISTRY_URL}"
    npm config get registry
fi

pwd 

ls -a

yarn install 

yarn build ${JIANMU_BUILD_ARG}

echo "{\"package_name\": $(cat package.json | jq .name),\"package_version\": $(cat package.json|jq .version)}" > /tmp/result.json
