#!/bin/sh

set -x
set -e

if [[ ! -z "${JIANMU_WORKSPACE}" ]]; then
    cd ${JIANMU_WORKSPACE}
fi

if [[ ! -z "${JIANMU_REGISTRY_URL}" ]]; then
    yarn config set registry "${JIANMU_REGISTRY_URL}"
    yarn config get registry
fi

if [[ ! -z "${JIANMU_DISTURL_URL}" ]]; then
    yarn config set disturl "${JIANMU_DISTURL_URL}"
    yarn config get disturl
fi

pwd 

ls -a

yarn install 

yarn build ${JIANMU_BUILD_ARG}

echo "{\"package_name\": $(cat package.json | jq .name),\"package_version\": $(cat package.json|jq .version)}" > /tmp/result.json
